//THERE ARE 4 TYPES OF CLASSES IN JAVA PROGRAMMING. PUBLIC, DEFAULT, PRIVATE AND PROTECTED.
public class FirstProgram //THIS IS THE OUTER CLASS. THE OUTER CLASS MAY BE PUBLIC OR DEFAULT. THE INNER CLASS CAN BE PRIVATE,PUBLIC,PROTECTED.
{
    public static void main(String args[])
    {
        System.out.print("\nHello Everyone!!!");
    }
}
//IN THIS CODE THERE ARE THREE WORDS STARTING WITH CAPITAL LETTERS.
// THESE ARE "FirstProgram"- WHICH IS DEFINED BY THE PROGRAMMER
//'String' & 'System' ARE PRE DEFINED CLASS. 
//AFTER WRITING A PRE-DEFINED CLASS IF (.) DOT OPERATOR IS USED THEN WE ARE ACCESSING A STATIC MEMBER OF A CLASS.